version: "3"
services:
  app:
    container_name: LiveLotAPI
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/usr/src/app'
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"